version: '3.8'

services:
  critorie-la-rodica:
    container_name: critorie-la-rodica
    build:
      context: .
      dockerfile: dockerfile
#    ports:
#      - "3003:80"
#    volumes:
#      - .:/app
    restart: unless-stopped
    networks:
      - bible-project-network

networks:
  bible-project-network:
    external: true
